version: '3.8'
services:
    todo-database:
        image: postgres:latest
        environment:
            - POSTGRES_DB=todo-database
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - "5432:5432"
