services:
    todo-database:
        image: postgres:16.3 # Keep in sync with the latest stable version -> https://www.postgresql.org/docs/release/
        environment:
            - POSTGRES_DB=todo-database
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - "5432:5432"
